const INITIALIZE_USER = "INITIALIZE_USER";
const UPDATE_USER_LOCATION = "UPDATE_USER_LOCATION";
const INITIALIZE_JOB_STATUS = "INITIALIZE_JOB_STATUS";
const UPDATE_JOB_STATUS = "UPDATE_JOB_STATUS";
const RESET_JOB_STATUS = "RESET_JOB_STATUS";

export default {
  INITIALIZE_USER,
  UPDATE_USER_LOCATION,
  INITIALIZE_JOB_STATUS,
  UPDATE_JOB_STATUS,
  RESET_JOB_STATUS,
};
